[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/forum"
  to = "/forum/index.html"
  status = 200

[[redirects]]
  from = "/forum/*"
  to = "/forum/index.html"
  status = 200
