[build]
  publish = "."
  functions = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/forum"
  to = "/forum/index.html"
  status = 200

[[redirects]]
  from = "/forum/*"
  to = "/forum/index.html"
  status = 200
